[project]
name = "ai-workspace"
version = "0.1.0"
description = "面向 Coding Agent 的通用工作区模板。"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "tencent"
url = "https://mirrors.tencent.com/pypi/simple/"
default = true
